<?php

/**
 * @file
 * Provided form text element Site API key to the Site Information Form
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter() for system_site_information_settings form
 */
function site_api_form_system_site_information_settings_alter(&$form, FormStateInterface &$form_state) {
  $config = \Drupal::config('system.site');
  $form['site_information']['siteapikey'] = [
    '#type' => 'textfield',
    '#title' => t('Site API Key'),
    '#default_value' => $config->get('siteapikey'),
    '#required' => FALSE,
  ];
  $form['site_information']['siteapikey']['#attributes']['placeholder'] = 'No API Key yet';
  $form['actions']['submit']['#value'] = t('Update Configuration');
  $form['#submit'][] = 'site_api_form_system_site_information_settings_submit';
}

/**
 * Submit Handler for system_site_information_settings form
 */
function site_api_form_system_site_information_settings_submit(array &$form, FormStateInterface $form_state) {
  $config = \Drupal::service('config.factory')->getEditable('system.site');
  $site_key = $form_state->getValue('siteapikey');
  $config->set('siteapikey', $site_key)->save();

  // Logg site key on save.
  \Drupal::logger('site_api')->notice(t('Site API Key has been saved with value: %value.'),
    array(
      '%value' => $site_key,
    ));
  
  \Drupal::messenger()->addMessage(t('Site API Key has been saved with value %value.', ['%value' => $site_key]));
}
